### ISSUE TITLE
项目无法编译成功，可以列举一下需要编译源码所依赖的环境吗？

### ISSUE THREAD

**Issue by tianshaokai** [iamyours/FFmpegAudioPlayer#1]
Support for CMake 3.7 and higher is a preview feature.
CMake was unable to find a build program corresponding to "Ninja".

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

**Comment by tianshaokai** [comment]
代码可以编译了，但无法点击跳转，不知道哪有问题

**Comment by iamyours** [comment]
> 代码可以编译了，但无法点击跳转，不知道哪有问题

你看看测试音频有没有放到对应的目录，还有错误日志是什么

**Comment by iamyours** [comment]
[https://www.jianshu.com/p/9cda76b7f63b](https://www.jianshu.com/p/9cda76b7f63b)编译环境博客中有介绍

**Comment by tianshaokai** [comment]
你的ndk版本是多少啊，我用15 16都不好用

**Comment by tianshaokai** [comment]
我试了好多版本ndk，cmakelist 文件内容就是不能变成正常绿色，不过代码中的架构不是都废弃了吗，作者那里编译怎么样呢？

**Comment by iamyours** [comment]
> 你的ndk版本是多少啊，我用15 16都不好用

ndk-r15c版本

**Comment by tianshaokai** [comment]
我的也是，代码虽然能运行，但cmakelist 文件就是白色，不是正常绿色，jni代码无法跳转

**Comment by iamyours** [comment]
其他平台编译脚本
[https://github.com/iamyours/FFmpegAudioPlayer/blob/master/build_android_all.sh](https://github.com/iamyours/FFmpegAudioPlayer/blob/master/build_android_all.sh)

**Comment by HYVincent** [comment]
Build command failed.
  Error while executing process D:\Vincent-Dev\Android-SDK\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\Vincent-Dev\TempProject\FFmpegAudioPlayer-master\app\.externalNativeBuild\cmake\debug\arm64-v8a --target native-lib}
  [1/1] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so
  FAILED: cmd.exe /C "cd . && D:\Vincent-Dev\Android-SDK\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android21 --gcc-toolchain=D:/Vincent-Dev/Android-SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/Vincent-Dev/Android-SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -std=gnu++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/audio-mix.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/AudioPlayer.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/opensles-test.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/player-test.cpp.o  ../../../../src/main/jniLibs/arm64-v8a/libavutil-55.so ../../../../src/main/jniLibs/arm64-v8a/libswresample-2.so ../../../../src/main/jniLibs/arm64-v8a/libavcodec-57.so ../../../../src/main/jniLibs/arm64-v8a/libavfilter-6.so ../../../../src/main/jniLibs/arm64-v8a/libswscale-4.so ../../../../src/main/jniLibs/arm64-v8a/libavformat-57.so -lOpenSLES -llog -landroid -latomic -lm && cd ."
  ../../../../src/main/jniLibs/arm64-v8a/libavutil-55.so: error adding symbols: File in wrong format
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by iamyours** [comment]
编译最好在linux/mac环境下，不太推荐在windows下编译，你可以装一个虚拟机或者在云主机上进行ffmpeg编译
