### ISSUE TITLE
用go重写了转码的部分,会fatal,可否指教一下?

### ISSUE THREAD

**Issue by kaiiak** [iamyours/FFmpegAudioPlayer#2]
代码如下，感谢
https://gist.github.com/kaiiak/4e5f058f4289153a525a54fbc43e756a

**Comment by iamyours** [comment]
这边编译的动态库是运行在Android环境下的，你这个是运行在哪个环境下？

**Comment by kaiiak** [comment]
@iamyours 是在mac下面运行的

**Comment by iamyours** [comment]
库文件不兼容，需要自己编译生成mac环境下的库文件，你可以试下这个下面的a文件
https://github.com/leixiaohua1020/simplest_ffmpeg_mobile/tree/master/simplest_ffmpeg_ios_transcoder

**Comment by kaiiak** [comment]
我是用的brew安装的ffmeeg，没有自己编译库文件

**Comment by iamyours** [comment]
这个就不清楚了，brew安装ffmpeg估计只能用ffmpeg命令，不能使用内置的库

**Comment by kaiiak** [comment]
非常感谢您的回答
