### ISSUE TITLE
so库打包成功，最后运行报错：Build command failed.

### ISSUE THREAD

**Issue by lxq666** [iamyours/FFmpegAudioPlayer#3]
android studio版本：3.4.0
FFmpeg：3.2.12
ndk版本：android-ndk-r15c
打包成功so库以后，添加到了新建的项目中，直接拷贝了你的CMakeLists里面的代码，build是没问题的，但运行到手机上的时候报错了：
`Build command failed.
Error while executing process /Users/wenba/android-sdk-macosx/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/wenba/AndroidStudioProjects/FFmpegDemo/app/.externalNativeBuild/cmake/debug/armeabi --target native-lib}

ninja: error: '/Users/.../app/src/main/cpp/src/main/jniLibs/armeabi/libavutil-55.so', needed by '/Users/.../app/build/intermediates/cmake/debug/obj/armeabi/libnative-lib.so', missing and no known rule to make it`
提示说找不到libavutil-55.so，但是Users/.../app/src/main/cpp/src/main/jniLibs/armeabi/libavutil-55.so'在这个路径下是能够找到libavutil-55.so这个库的。

**Comment by lxq666** [comment]
对了我的CmakeLists.txt在app/src/main/cpp的文件夹下面，但是我把这个文件挪到app/下面，结果报了更多的错误：
`Build command failed.
Error while executing process /Users/wenba/android-sdk-macosx/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/wenba/AndroidStudioProjects/FFmpegDemo/app/.externalNativeBuild/cmake/debug/armeabi --target native-lib}
[1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
[2/2] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi/libnative-lib.so
FAILED: : && /Users/wenba/android-ndk-r15c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv5te-none-linux-androideabi --gcc-toolchain=/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/wenba/android-ndk-r15c/sysroot -fPIC -isystem /Users/wenba/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -std=gnu++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a --sysroot /Users/wenba/android-ndk-r15c/platforms/android-15/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi/libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o  ../../../../src/main/jniLibs/armeabi/libavutil-55.so -lswresample-2 -lavcodec-57 -lavfilter-6 -lswscale-4 -lavformat-57 -lOpenSLES -llog -landroid -lm "/Users/wenba/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/libgnustl_static.a" "-latomic" && :
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lswresample-2
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavcodec-57
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavfilter-6
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lswscale-4
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavformat-57
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
`

**Comment by iamyours** [comment]
看下app/bulid.gradle的配置,你对比一下
```
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "io.github.iamyours.ffmpegaudioplayer"
        minSdkVersion 14
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11"
            }
            ndk{
                abiFilters "armeabi", "x86","x86_64"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}
```

**Comment by lxq666** [comment]
我的build.gradle文件：
```
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.ffmpegdemo"
        minSdkVersion 14
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11"
            }
            ndk{
                abiFilters "armeabi"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.6.0"
        }
    }
}
```
abiFilters改成： "armeabi", "x86","x86_64"
注释version:"3.6.0"
还是报原来的错误。

**Comment by iamyours** [comment]
CMakeLists.txt放到app目录下，里面的配置是以app为根目录的

**Comment by lxq666** [comment]
报了这样的错：
```
Build command failed.
Error while executing process /Users/wenba/android-sdk-macosx/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/wenba/AndroidStudioProjects/FFmpegDemo/app/.externalNativeBuild/cmake/debug/armeabi --target native-lib}
[1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi/libnative-lib.so
FAILED: : && /Users/wenba/android-ndk-r15c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv5te-none-linux-androideabi --gcc-toolchain=/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/wenba/android-ndk-r15c/sysroot -fPIC -isystem /Users/wenba/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -std=gnu++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a --sysroot /Users/wenba/android-ndk-r15c/platforms/android-14/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi/libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o  ../../../../src/main/jniLibs/armeabi/libavutil-55.so -lswresample-2 -lavcodec-57 -lavfilter-6 -lswscale-4 -lavformat-57 -lOpenSLES -llog -landroid -lm "/Users/wenba/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/libgnustl_static.a" "-latomic" && :
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lswresample-2
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavcodec-57
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavfilter-6
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lswscale-4
/Users/wenba/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lavformat-57
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by iamyours** [comment]
你先试试用我这边到so文件编译，看看是不是so文件有问题

**Comment by lxq666** [comment]
确实是so库的问题，可能是我项目中使用的ndk版本和bash_profile中配置的版本不同导致的。我又重新编译了一遍so库，可以运行了。
